In [1]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.11/site-packages (1.26.4)

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
airbnb = pd.read_csv('air-bnb-listings.csv', encoding='UTF-8', delimiter=';')
airbnb

,Room ID,Name,Host ID,Neighbourhood,Room type,Room Price,Minimum nights,Number of reviews,Date last review,Number of reviews per month,Rooms rent by the host,Availibility,Updated Date,City,Country,Coordinates,Location
0,21813271,"Double room in Chueca, with private bathroom F 02",132022481,Universidad,Private room,45,1,167,2020-03-14,5.19,46,136,2020-07-17,Madrid,Spain,"40.423192260888946, -3.7010886688779783","Spain, Madrid, Universidad"
1,21877634,Sunny room with balcony in pretty family house,10169235,Ciudad Jardín,Private room,26,7,6,2020-03-08,0.65,2,179,2020-07-17,Madrid,Spain,"40.45004385318866, -3.6712841871122457","Spain, Madrid, Ciudad Jardín"
2,21931400,Apartamento muy cuco en el barrio de Chamberí,111949695,Trafalgar,Entire home/apt,57,1,5,2020-03-02,0.67,1,0,2020-07-17,Madrid,Spain,"40.43042274619744, -3.701693596173804","Spain, Madrid, Trafalgar"
3,21945665,Design apartment in Heart of Madrid,93930798,Castellana,Entire home/apt,190,3,3,2019-10-06,0.18,2,179,2020-07-17,Madrid,Spain,"40.43057627460486, -3.6869397877080177","Spain, Madrid, Castellana"
4,21955381,Trendy hip Malasaña duplex for art&design lovers,69805790,Universidad,Entire home/apt,75,5,22,2020-01-19,0.71,2,364,2020-07-17,Madrid,Spain,"40.42584028788459, -3.7030496318151873","Spain, Madrid, Universidad"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21273,40024546,Espectacular Apto. Centro de Madrid C/Infantas...,40877988,Justicia,Entire home/apt,120,2,11,2020-03-19,1.39,61,104,2020-07-17,Madrid,Spain,"40.41859791602588, -3.696677711709054","Spain, Madrid, Justicia"
21274,40025038,MONTE ESQUINZA,28038703,Almagro,Entire home/apt,5000,3,3,2020-05-20,0.45,121,241,2020-07-17,Madrid,Spain,"40.427877170350875, -3.6920417052279197","Spain, Madrid, Almagro"
21275,40101840,Estudio con terraza en el Rastro.,309468247,Embajadores,Entire home/apt,90,1,3,2019-12-30,0.39,1,363,2020-07-17,Madrid,Spain,"40.40710346245265, -3.7111004890020594","Spain, Madrid, Embajadores"
21276,40124833,Estudio Superior Con Balcón 2pax,307123621,Sol,Entire home/apt,45,2,3,2020-07-03,0.53,21,158,2020-07-17,Madrid,Spain,"40.41807959756484, -3.7058389385301087","Spain, Madrid, Sol"
21277,40173415,Cozy apartment in the center of Madrid,304858865,Prosperidad,Private room,35,1,3,2020-01-03,0.40,2,90,2020-07-17,Madrid,Spain,"40.4477432483765, -3.6685643121069904","Spain, Madrid, Prosperidad"

Tras explorar los datos del dataset, se ha comprobado que aún estando filtrados para que fuesen datos de Madrid, había datos de alojamientos que no pertenecían a Madrid, por lo que se han eliminado los datos de alojamientos que no pertenecían a Madrid con el siguiente código.
También se ha observado que había una columna con una fecha, que corresponde al útimo día en que se actualizaron los inmuebles, que para todos los alojamientos es la misma fecha, por lo que pensamos que no aporta valor.
No se han eliminado los datos que contienen campos nulos en la columna reviews puesto que pensamos que para el momento de hacer el modelo para predecir el precio de un alojamiento supondría una pérdida de datos válidos para el modelo.

In [5]:
airbnb = pd.read_csv('air-bnb-listings.csv', encoding='UTF-8', delimiter=';')
Madrid = airbnb['City']== 'Madrid'
Madrid
airbnbMadrid = airbnb[Madrid]
del airbnbMadrid['Updated Date']
airbnbMadrid.to_csv('aribnbMadrid.csv', encoding='utf8', sep='\t', index=False)
airbnbMadrid

,Room ID,Name,Host ID,Neighbourhood,Room type,Room Price,Minimum nights,Number of reviews,Date last review,Number of reviews per month,Rooms rent by the host,Availibility,City,Country,Coordinates,Location
0,21813271,"Double room in Chueca, with private bathroom F 02",132022481,Universidad,Private room,45,1,167,2020-03-14,5.19,46,136,Madrid,Spain,"40.423192260888946, -3.7010886688779783","Spain, Madrid, Universidad"
1,21877634,Sunny room with balcony in pretty family house,10169235,Ciudad Jardín,Private room,26,7,6,2020-03-08,0.65,2,179,Madrid,Spain,"40.45004385318866, -3.6712841871122457","Spain, Madrid, Ciudad Jardín"
2,21931400,Apartamento muy cuco en el barrio de Chamberí,111949695,Trafalgar,Entire home/apt,57,1,5,2020-03-02,0.67,1,0,Madrid,Spain,"40.43042274619744, -3.701693596173804","Spain, Madrid, Trafalgar"
3,21945665,Design apartment in Heart of Madrid,93930798,Castellana,Entire home/apt,190,3,3,2019-10-06,0.18,2,179,Madrid,Spain,"40.43057627460486, -3.6869397877080177","Spain, Madrid, Castellana"
4,21955381,Trendy hip Malasaña duplex for art&design lovers,69805790,Universidad,Entire home/apt,75,5,22,2020-01-19,0.71,2,364,Madrid,Spain,"40.42584028788459, -3.7030496318151873","Spain, Madrid, Universidad"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21273,40024546,Espectacular Apto. Centro de Madrid C/Infantas...,40877988,Justicia,Entire home/apt,120,2,11,2020-03-19,1.39,61,104,Madrid,Spain,"40.41859791602588, -3.696677711709054","Spain, Madrid, Justicia"
21274,40025038,MONTE ESQUINZA,28038703,Almagro,Entire home/apt,5000,3,3,2020-05-20,0.45,121,241,Madrid,Spain,"40.427877170350875, -3.6920417052279197","Spain, Madrid, Almagro"
21275,40101840,Estudio con terraza en el Rastro.,309468247,Embajadores,Entire home/apt,90,1,3,2019-12-30,0.39,1,363,Madrid,Spain,"40.40710346245265, -3.7111004890020594","Spain, Madrid, Embajadores"
21276,40124833,Estudio Superior Con Balcón 2pax,307123621,Sol,Entire home/apt,45,2,3,2020-07-03,0.53,21,158,Madrid,Spain,"40.41807959756484, -3.7058389385301087","Spain, Madrid, Sol"
21277,40173415,Cozy apartment in the center of Madrid,304858865,Prosperidad,Private room,35,1,3,2020-01-03,0.40,2,90,Madrid,Spain,"40.4477432483765, -3.6685643121069904","Spain, Madrid, Prosperidad"

Para crear la base de datos se ha utilizado el siguiente codigo:
create schema airbnb;
set schema 'airbnb';
Aquí se importan los datos del csv creado una vez filtrados los datos que sean solo de Madrid y eliminada la columna que hemos desechado, para crear la tabla tmp_airbnb;
select  * from temp_airbnb ta;

create table alojamiento(
	HostID int4 primary key,
	Name varchar(500),
	RommType varchar(500),
	RoomPrice int4,
	RoomId int4);
	
create table availibility(
	Id smallserial primary key,
	RoomId int4,
	RoomsRentByTheHost int4,
	Availibility int4);
	
create table neighbourhood (
	Id smallserial primary key,
	Neighbourhood varchar(500),
	Country varchar(500),
	City varchar(500),
	RoomId int4);
	
create table reviews (
	Id smallserial primary key,
	HostID int4,
	NumberOfReviews int4,
	ReviewsPerMonth int4,
	DateLastReview varchar(500));
	
insert into alojamiento (HostID, Name, RommType, RoomPrice, RoomId)
select distinct ta."Room ID" , ta."Name" , ta."Room type" ,ta."Room Price" , ta."Room ID" from temp_airbnb ta 

insert into availibility (RoomId,RoomsRentByTheHost,Availibility)
select distinct ta."Room ID" ,ta."Rooms rent by the host" ,ta."Availibility" from temp_airbnb ta

insert  into neighbourhood (Neighbourhood,Country,City, RoomId)
select distinct  ta."Neighbourhood" ,ta."Country" ,ta."City" ,ta."Room ID" from temp_airbnb ta

insert into reviews (HostID,NumberOfReviews,ReviewsPerMonth,DateLastReview)
select distinct  ta."Host ID" ,ta."Number of reviews" , ta."Number of reviews per month" ,ta."Date last review" from temp_airbnb ta



alter table alojamiento  add CONSTRAINT fk_roomid_alojamiento FOREIGN KEY (RoomId) REFERENCES Neighbourhood(Id);
alter table availibility add CONSTRAINT fk_roomid_availability FOREIGN KEY (RoomId) REFERENCES Alojamiento(RoomId);
alter table availibility add CONSTRAINT fk_hostid_availability FOREIGN KEY (RoomsRentByTheByHost) REFERENCES Alojamiento(HostId);
alter table reviews add CONSTRAINT fk_hostid_reviews FOREIGN KEY (HostId) REFERENCES Alojamiento(HostId);